export const ImageConst = {
  // plus_png: require('../../asset/Image/plus.png'),
  // email_png: require('../../asset/Image/email.png'),
  // user_png: require('../../asset/Image/user.png'),
  // padlock_png: require('../../asset/Image/p'),
  // google_png: require('../../asset/Image/google.png'),
  // facebook_png: require('../../asset/Image/facebook.png'),
  // arrow_png: require('../../asset/Image/arrow.png'),
  // add_friend_png: require('../../asset/Image/add-friend.png'),
  // cancel_png: require('../../asset/Image/cancel.png'),
  // search_interface_symbol_png: require('../../asset/Image/search-interface-symbol.png'),
  // group_png: require('../../asset/Image/group.png'),
  // add_user_png: require('../../asset/Image/add-user.png'),
  // multiple_users_silhouette_png: require('../../asset/Image/multiple-users-silhouette.png'),
  // images_removebg_preview_png: require('../../asset/Image/images-removebg-preview.png'),
  // call_png: require('../../asset/Image/call.png'),
  // bell_png: require('../../asset/Image/bell.png'),
  // options_png: require('../../asset/Image/options.png'),
  // camera: require('../../asset/Image/photo-camera-interface-symbol-for-button.png'),
  // gallery_png: require('../../asset/Image/gallery.png'),
  // send_message_png: require('../../asset/Image/send-message.png'),
  // zoom_png: require('../../asset/Image/zoom.png'),
  // user1_png: require('../../asset/Image/user(1).png'),
};
